[package]
name = "tokio-page-faults"
version = "0.1.0"
edition = "2024"

[dependencies]
atomic-wait = "1"
libc = { version = "0.2", default-features = false }
tokio = { version = "1", default-features = false, features = ["rt-multi-thread", "sync"] }
